image: node:10.17.0-alpine

cache:
  key: 'alpine'
  paths:
    - node_modules/

stages:
  - test
  - build
  - e2etest
  - autodeploy

test:
  stage: test
  script:
    - npm install
    - NODE_ENV=ci npm run test
  tags:
    - docker

docker build:
  image: docker:stable
  stage: build
  script:
    - docker info
    - docker build . -t dmsc/duo-frontend
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push dmsc/duo-frontend
  tags:
    - docker

e2etest:
  image: tiangolo/docker-with-compose
  stage: e2etest
  script:
    - echo "CI_COMMIT_BRANCH $CI_COMMIT_BRANCH"
    - TAGS_JSON=$(curl -s -o /dev/null -w "%{http_code}" https://registry.hub.docker.com/v1/repositories/dmsc/duo-frontend/tags)
    - apk add jq
    - TAG_COUNT=echo $TAGS_JSON | $(jq -c '.[] | select(.name | contains("release"))' | jq -s '. | length')
    - if [ "$TAG_COUNT" != 0 ]; then     export TAG=$CI_COMMIT_BRANCH; else     export TAG=latest; fi    - apk add git
    - echo "TAG $TAG"
    - apk add git
    - rm -rf duo-backend
    - git clone https://gitlab.esss.lu.se/swap/duo-backend.git
    - docker-compose -f docker-compose.e2e.yaml rm
    - docker-compose -f docker-compose.e2e.yaml down --remove-orphans
    - docker-compose -f docker-compose.e2e.yaml pull
    - docker-compose -f docker-compose.e2e.yaml build
    - docker-compose -f docker-compose.e2e.yaml up --exit-code-from cypress
    - docker-compose -f docker-compose.e2e.yaml down
  tags:
    - docker

autodeploy:
  image: ubuntu:latest
  stage: autodeploy
  script:
    - echo $CI_COMMIT_SHA
    - apt-get update -qq
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY_GEN")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh jekabskarklins@scicat09.esss.lu.se "/home/jekabskarklins/duo-kubernetes/frontend/autodeploy.sh dev"
  tags:
    - dind
  only:
    - develop
