# Use postgres/example user/password credentials
version: '3.1'

services:
  backend:
    image: 'dmsc/duo-backend:${USER_OFFICE_BACKEND_TAG}'
    environment:
      DATABASE_URL: postgres://duouser:duopassword@db:5432/duo
      secret: qMyLZALzs229ybdQXNyzYRdju7X784TH
      tokenLife: 7d
      baseURL: localhost:3000
      SPARKPOST_TOKEN: dummytoken
      NODE_ENV: development
      UO_FEATURE_DISABLE_MESSAGE_BROKER: 1
      UO_FEATURE_DISABLE_EAM: 1
      USER_OFFICE_FACTORY_ENDPOINT: ${USER_OFFICE_FACTORY_ENDPOINT}
    labels:
      - 'traefik.frontend.rule=PathPrefix:/api, /graphql, /downloads, /files, /download, /uploads'
      - 'traefik.port=4000'
    volumes:
      - './${USER_OFFICE_BACKEND_DIR}/db_patches:/home/node/app/db_patches'

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: duopassword
      POSTGRES_USER: duouser
      POSTGRES_DB: duo
      INCLUDE_SEEDS: ${INCLUDE_SEEDS}
    ports:
      - 5432:5432
    volumes:
      - './${USER_OFFICE_BACKEND_DIR}/db_patches/:/docker-entrypoint-initdb.d/'
